import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import QueryProvider from "./provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "To-Do List",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<nav className="flex gap-10">
					<Link href={`/`}>Home</Link>
					<Link href={`/about`}>About</Link>
					<Link href={`/report`}>Report</Link>
					<Link href={`/todos-csr`}>To-Dos-CSR</Link>
					<Link href={`/todos-ssr`}>To-Dos-SSR</Link>
				</nav>
				<QueryProvider>{children}</QueryProvider>
			</body>
		</html>
	);
}
